### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by remg427**
modification for #24 and partly #13/#16
doc needs still to be aligned once confirmed it works

### CODE REVIEW

**Comment by LetMeR00t** [comment]
Hi @remg427, 
Thanks for the PR.
It’s however malformed for some files 
- some files are modified with a space or a semi colon
- some files have permissions changed (which is not good for the App Inspector) - As a matter of fact, the app builder itself is changing these permissions but it’s not allowed when submitted to the Splunkbase. You will just have to do a chmod command on files with permission changed. Or I will just handle this before submission ? 

Right thing is that you exported the project from app builder and the app itself

**Comment by remg427** [comment]
Hi.
Files with a space I don't get it.
It is only exported from AOB this time.
Finally I prefer my way of working
Could you restore proper permissions?
Otherwise I will update PR latter
-- 
Sent with K-9 Mail.

**Comment by LetMeR00t** [comment]
Forget about spaces, i was not well wake up.
If you are not confortable with the app builder usage I understand but I will keep it on my side to facilitate integrations. In that case, I will accept your PR but I will have to regenerate the Splunk app and the project from app builder but it’s okay.
I will integrate your new things ASAP

**Comment by LetMeR00t** [comment]
@remg427,
I noticed some important changes on dashboards using .. templates ?
I will need time to understand how it works as I never done this before.

**Comment by LetMeR00t** [comment]
Again, next time just push the new files without the app builder or so and I will handle the merge on my side.

**Review by LetMeR00t — APPROVED** [review]
This will be implemented and adapted on my side.
Thank you

**Pull request merged**
